#!/bin/bash


set -e

# Show help message if user provides -h or --help option
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  echo "
Description :
  This script is for manually change date and time.
How to use:
  sms_date_manual [date][time]
  example :
    sms_date_manual 2023/05/14 14:15:00
  exit 0
fi

> /etc/conf.d/ntp-client
/etc/init.d/ntp-clint restart

# Combine the date and time arguments into a single string
new_datetime="$1 $2"

# Set the system date and time to the user's input
date -s "$new_datetime"

# Display the new system date and time
echo "The system date and time : $(date +"%Y-%m-%d %H:%M:%S")"
