#!/bin/bash


set -e

# Show help message if user provides -h or --help option
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  echo "
Description :
  This script displays the status of system date.
How to use:
  sms_osinfo"
  exit 0
fi

#echo "\"version-os\"; {"
VERSION=$(cat /etc/gentoo-release | cut -d ' ' -f 5)
#echo "\"Gentoo Linux version\" : \"$VERSION\""
echo "\"version-os\" : $VERSION"

#echo "}"

