#!/bin/bash

# Get the name of the script and its inputs from command-line arguments
script_name=$1
shift
script_inputs=$@

# Check if the script exists
if [ ! -f "$script_name" ]; then
  echo "Error: Script '$script_name' not found."
  exit 1
fi

# Run the script with its inputs
bash "$script_name" $script_inputs
exit_code=$?


exit $exit_code

