#!/bin/bash

set -e

# Show help message if user provides -h or --help option
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  echo "
Description :
  This script is for automatic setting the date and time.
How to use:
  Script name + interface name
How to use:
  The name of the script + serverip"
  exit 0
fi


serverip=$1

> /etc/conf.d/ntp-client
#echo -e "NTPCLINT_CMD=\"ntpdate\"\nNTPCLINT_OPTS=\"-s -b -u 10.100.40.115\"" > /etc/conf.d/ntp-clint
echo -e "NTPCLINT_CMD=\"ntpdate\"\nNTPCLINT_OPTS=\"-s -b -u '$serverip'\"" > /etc/conf.d/ntp-clint
/etc/init.d/ntp-clint restart

