#!/bin/bash

set -e

# Show help message if user provides -h or --help option
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  echo "
Description :
  This script is for running scripts that do need sudo.

How to use:
  The name of the script and the script you want to run."
  exit 0
fi

# Get the name of the script and its inputs from command-line arguments
script_name=$1
shift
script_inputs=$@

# Check if the script exists
if [ ! -f "$script_name" ]; then
  echo "Error: Script '$script_name' not found."
  exit 1
fi

# Run the script with its inputs
sudo bash "$script_name" $script_inputs

exit_code=$?


exit $exit_code

